config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :users, except: [:index, :destroy]
  resources :questions, only: [:index]
  resources :exams, except: :destroy
  resources :categories, only: [:index] do
    resources :exams, only: [:new, :create, :show]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
    get "/edit" => "devise/registrations#edit"
  end

  namespace :admin do
    resources :users
    resources :categories
    resources :exams, except: [:edit, :update]
    resources :questions
    root "exams#index"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, Category
      can :manage, Question
    else
      can :create, Exam
      can [:read, :update], Exam, user_id: user.id
      can :read, Question
      can :read, Category
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :content, presence: true, length: {minimum: 2, maximum: 20}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, length: {minimum: 2, maximum: 50}
  validates :name, uniqueness: true
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :results
  has_many :questions, through: :results

  before_save :make_random_questions, unless: :is_done?
  before_update :update_correct_answers, :mark_the_exam, if: :is_done?

  accepts_nested_attributes_for :results, allow_destroy: true,
                                          reject_if: :all_blank

  scope :order_by_created_at, -> {order created_at: :DESC}
  scope :inactive_exams, ->time {where("done = 'f' AND created_at < '#{time.ago.to_s(:db)}'")}

  private
  def make_random_questions
    @questions = category.questions.random_questions
    @questions.each {|question| results.build question: question}
  end

  def mark_the_exam
    self.mark = results.select{|result| result.answer_correct}.count
  end

  def update_correct_answers
    results.each{|result| result.correct = result.answer_correct unless result.answer_id.nil?}
  end

  def is_done?
    self.done?
  end

  def self.delete_inactive_exams
    inactive_exams(Settings.expired_time.seconds).each {|exam| exam.destroy}
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :exams, through: :results

  scope :random_questions, -> {limit(Settings.limited_number_of_records).order("RANDOM()")}
  
  validates :content, presence: true, length: {minimum: 2, maximum: 20}

  accepts_nested_attributes_for :answers, allow_destroy: true,
                                          reject_if: :all_blank
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :exam
  belongs_to :question
  belongs_to :answer

  delegate :correct, to: :answer, prefix: true, allow_nil: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :exams, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @categories.paginate page: params[:page],
                         per_page: Settings.page_size
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :success
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = t :success
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      flash[:success] = t :success
    else
      flash[:danger] = t :fail
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @questions = @questions.paginate page: params[:page],
                                     per_page: Settings.page_size
  end

  def new
    @question = Question.new
    @categories = Category.all
    4.times {@question.answers.build}
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = t :success
      redirect_to admin_questions_path
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    @question = Question.find params[:id]
    @categories = Category.all
  end

  def update
    @question = Question.find params[:id]
    if @question.update_attributes question_params
      flash[:success] = t :success
      redirect_to admin_questions_path
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @question = Question.find params[:id]
    if @question.destroy
      flash[:success] = t :success
    else
      flash[:danger] = t :fail
    end
    redirect_to admin_questions_path
  end

  private
  def question_params
    params.require(:question).permit :content, :category_id,
      answers_attributes: [:id, :content, :correct, :_destroy]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, except: :index

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.js
      format.html {redirect_to users_url}
      format.json {head :no_content}
    end
  end

  private
  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit :email, :password,
                                 :password_confirmation, :admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @categories.paginate page: params[:page],
                         per_page: Settings.page_size
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exams = current_user.exams.order_by_created_at
              .paginate page: params[:page], per_page: Settings.exam_page_size
    @exam = Exam.new
    @categories = Category.all
  end

  def show
  end

  def create
    @exam.user = current_user
    if @exam.save
      flash[:success] = t :success
    else
      flash[:fail] = t :fail
    end
    redirect_to exams_path
  end

  def edit
  end

  def update
    if @exam.update_attributes exam_params
      redirect_to @exam
    else
      redirect_to :back
    end
  end

  private
  def exam_params
    params.require(:exam).permit :category_id, :done, results_attributes: [:id, :answer_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @questions = @questions.paginate page: params[:page],
                                     per_page: Settings.page_size
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields name, f, association
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to name, "#",
            onclick: h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"),
            remote: true
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td class="col-md-4" data-no-turbolink="true">
    <%= link_to t(:edit), edit_admin_category_path(category.id),
                class: "btn btn-primary col-md-3" %>
    <%= link_to t(:delete), admin_category_path(category.id), method: :delete,
                data: {confirm: t(:confirm)},
                class: "btn btn-primary col-md-3 col-md-offset-1" %>
    </td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <p>
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </p>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t :edit %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= t :categories %></h1>
    <p>
      <%= link_to t(:new), new_admin_category_path, class: "btn btn-primary" %>
    </p>
    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th><%= t :categories %></th>
      </tr>
      <%= render @categories %>
    </table>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h1><%= t :new %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr id="user_<%= user.id %>">
  <td><%= user.email %></td>
  <td>
    <% unless user.admin? %>
      <%= link_to t(:delete_link), admin_user_path(user), method: :delete,
        remote: true, data: {confirm: t(:confirm_notification)} %>
    <% end %>
  </td>
</tr>

app/views/admin/users/destroy.js.erb
$('#user_<%= @user.id %>').fadeOut();

app/views/admin/users/index.html.erb
<div class="container">
 
  <h2><%= t(:all_accounts) %></h2>

  <div class="new-user"></div>
  
  <%= will_paginate %>
  <table id class="table table-bordered table-striped">
    <thead>
    <tr>
      <th><%= t(:email) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody id="users">
      <%= render @users %>
    </tbody>
  </table>

</div>

app/views/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
</tr>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= t :categories %></h1>
    <table class="table table-bordered">
      <tr>
        <th><%= t :id %></th>
        <th><%= t :categories %></th>
      </tr>
      <%= render @categories %>
    </table>
  </div>
</div>

app/views/exams/_exam.html.erb
<span class="col-md-1">
</span>

<li>
  <span class="col-md-4">
    <%= exam.category.name %>
  </span>

  <span class="col-md-4">
    <% if exam.done? %>
      <%= link_to t(:view), exam_path(exam) %>
    <% else %>
      <%= link_to t(:start), edit_exam_path(exam) %>
    <% end %>
  </span>
</li>
<br>

app/views/exams/_row.html.erb
<tr>
  <td>
    <% if object.correct? %>
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    <% else %>
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    <% end %>
  </td>
  <td>
    <%= object.question.content %>
  </td>
</tr>

app/views/exams/edit.html.erb
<h1><%= t :exam %></h1>
<br>

<div id="clockcontainer">
  <h3><%= t :time_left %></h3>
  <div id="countdown"></div>
</div>

<%= form_for @exam do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.hidden_field :done, value: true %>

  <%= f.fields_for :results do |builder| %>
    <%= render "result_form", f: builder %>
  <% end %>
  
  <div class="row">
    <%= f.submit t(:submit), class: "btn btn-primary", id: "submit_button", data: {confirm: t(:confirm_notification)} %>
  </div>

  <br><br><br><br><br><br>
<% end %>

app/views/exams/index.html.erb
<% provide :title, t(:all_exams) %>
<h1><%= t :all_exams %></h1>
<br><br>
<div class="row">
  <div class="col-md-3">
  </div>

  <div class="col-md-3">
    <%= form_for @exam do |f| %>
      <div class="border-c">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <table class="table table-bordered">
          <% @categories.each_with_index do |category, index| %>
            <tr>
              <td><%= f.radio_button :category_id, category.id, checked: index == 0 %></td>
              <td><%= category.name %></td>
            </tr>
          <% end %>
        </table>
        <%= f.submit t(:create_new_exam), class: "start-new btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-1">
  </div>

  <div class="col-md-4">
    <div class="exams">
      <%= render @exams %>
    </div>
    <%= will_paginate %>
  </div>
</div>
<br>

app/views/exams/show.html.erb
<div class="row">
  <h2><%= t :test_result %></h2>

  <div class="col-md-8 element one">
    <%= render @exam.results %>
  </div>

  <div class="col-md-3 element two">
    <p><%= t :result %><%= @exam.mark %>/10</p>
    <p><%= t :test_date %>: <%= @exam.updated_at %></p>
    <table class="table table-bordered">
      <tr>
        <th><%= t :correct %></th>
        <th><%= t :question %></th>
      </tr>
      <% @exam.results.each do |result| %>
        <%= render "exams/row", object: result %>
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <%= link_to "Framgia Vietnam", "http://recruit.framgia.vn/" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Framgia Test App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to t(:home), root_path %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li>
              <%= link_to t(:all_users), admin_users_path %>
            </li>
            <li>
              <%= link_to t(:categories), admin_categories_path %>
            </li>
            <li>
              <%= link_to t(:questions), admin_questions_path %>
            </li>
          <% else %>
            <li>
              <%= link_to t(:exams), exams_path %>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(:account) %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:edit), edit_path %></li>
              <li><%= link_to t(:logout), logout_path%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:login), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Framgia Test App</title>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.id %></td>
  <td><%= question.content %></td>
  <td><%= question.category.name %></td>  
</tr>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= t :questions %></h1>
    <div class="col-md-6 col-md-offset-3 paginate">
      <%= will_paginate @questions %>
    </div>
    <table class="table table-bordered">
      <tr>
        <th><%= t :id %></th>
        <th><%= t :questions %></th>
        <th><%= t :category %></th>
      </tr>
      <%= render @questions %>
    </table>
    <div class="col-md-6 col-md-offset-3 paginate">
      <%= will_paginate @questions %>
    </div>
  </div>
</div>

app/views/results/_result.html.erb
<div class="row">
  <div class="col-md-5">
    <h2><%= result.question.content %></h2>
  </div>
  <div class="col-md-6">
    <table class="table table-bordered">
      <% result.question.answers.each do |answer| %>
        <tr>
          <% if answer.id == result.answer_id %>
            <td>
              <%= radio_button_tag "result[#{result.id}]", result.id, true, disabled: true %>
            </td>
            <td>
              <b><%= answer.content %></b>
            </td>
          <% else %>
            <td>
              <%= radio_button_tag "result[#{result.id}]", result.id, false, disabled: true %>
            </td>
            <td>
              <%= answer.content %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <% if result.correct? %>
      <div class="checkbox">
        <label>
          <input type="checkbox" class="checkbox inline" name="checkbox" value="value" checked="checked" disabled="disabled">
          <%= t :correct_answer %>
        </label>
      </div>
    <% else %>
      <div class="checkbox">
        <label style="color: red">
          <input type="checkbox" class="checkbox inline" name="checkbox" value="value" disabled="disabled">
          <%= t :correct_answer %>
        </label>
      </div>
    <% end %>
  </div>
</div>
<hr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <%= pluralize object.errors.count, t(:error) %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t(:welcome_1) %></h1>
  <h2><%= t(:welcome_2) %></h2>
  <% unless user_signed_in? %>
    <%= link_to t(:sign_up), signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%- if controller_name != "sessions" %>
      <%= link_to t(:login), new_session_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.registerable? && controller_name != "registrations" %>
      <%= link_to t(:signup), new_registration_path(resource_name) %><br />
    <% end -%>
  </div>
</div>